version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:3001
    depends_on:
      - backend
    networks:
      - guess-pokemon

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - ./public:/app/public
      - /app/backend/node_modules
      - /app/shared/node_modules
    environment:
      - BACKEND_PORT=3001
      - FRONTEND_URL=http://frontend:5173
    networks:
      - guess-pokemon

networks:
  guess-pokemon:
    driver: bridge
